:github-readme: ../../../README.adoc
:main-pom: ../../../pom.xml
:example-nav-pom: ../../../examples/create_navigation/pom.xml
:example-css-pom: ../../../examples/replace_css/pom.xml
:example-man-pom: ../../../examples/build_example_manual/pom.xml

include::{github-readme}[tags=vardef]

:projectpage: https://github.com/{gh-repo-owner}/{gh-repo-name}

include::{github-readme}[tags=header]

== URLs

* link:{homepage}[Project home] (this page)
* link:{projectpage}[GitHub project]
* link:{bintraypage}[Binaries on Bintray]
* link:{issues}[Issue tracker]

TIP: Do you want to improve this page? Please gh:edit[link-text='edit it on GitHub'].

include::{github-readme}[tags=description]

Here is a detailed description of what you can do:

* Ressource delivery (like images and css): they are moved in subfolders and their path in the HTML file is modified.
** images are moved in a `images/` subfolder.
** css are moved in a `css/` subfolder.
* CSS replacement: it is possible to replace some CSS file with other ones.
* Link to listing and images are replaced (work around for link:{adoc_issue_858}[#858]). Your need these configurations in your asciidoc files:
** `:figure-caption: Figure` (this is already the default).
** `:listing-caption: Listing`.
* Navigation link: Multiple HTML pages are connected together with "Previous", "Next", "Home" links.
* PDF File are copied to the correct location.
* The HTML output can be zipped.

== Usage

The maven plugin is available in link:{bintray_repo}[my maven repository on Bintray], you can use this in your POM:

[source,xml]
----
include::{main-pom}[tags="pluginRepositories",indent="0"]
----

=== Example 1: Create navigation

This example adds some navigation bar in the html files, given a list of pages.

[source,xml]
----
include::{example-nav-pom}[tags="main",indent="0"]
----

Complete example: gh:viewdir[path='examples/create_navigation/', link-text='create_navigation'].

=== Example 2: Replace CSS

This example replaces the CSS files definition in the HTML.

[source,xml]
----
include::{example-css-pom}[tags="main",indent="0"]
----

Complete example: gh:viewdir[path='examples/replace_css/', link-text='replace_css'].

=== Example 3: Example Manual

Given an Asciidoctor output, this example prepare the doc for publication.

[source,xml]
----
include::{example-man-pom}[tags="main",indent="0"]
----

Complete example: gh:viewdir[path='examples/build_example_manual/', link-text='build_example_manual'].


== Code

As for any maven plugin, the source code of the plugin is available in the gh:viewdir[path='src', link-text='src'] folder.

There is an Eclipse Oomph Setup Task to import this project: link:{oomph_setup}[{oomph-file}]

If you prefer to import the project manually, here is how you can do it:

* Clone or add this repository using the "Git Repositories" view.
* Start the "Import Projects..." wizard on the "Working Directory" folder and pick the option "Import as general project".
* Back in the Package Explorer view, select "Configure" > "Convert to Maven Project" on the project.

=== Build

Run maven install on the root pom file:

  mvn install


include::{github-readme}[tags=contact-section]

include::{github-readme}[tags=license-section]

